language: android
android:
  components:
    - android-15
    - android-23
    - build-tools-22.0.1
    - extra
jdk:
  - oraclejdk8
notifications:
  email: false
  
script: cd <dir of android project>/ && ./gradlew build
