before_install: cd TheResistance
language: android

android:
  components:
    - android-23
    - build-tools-23.0.1
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # get emulator
    - sys-img-armeabi-v7a-android-21


# because we mention this section, Travis no longer builds our
# project automagestically. We have to explicitly call our build commands.
script:
  - cd ../TheResistance
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

  # explicitly build frontend
  - gradle build
  - ./gradlew connectedAndroidTest
